### ISSUE TITLE
Contacts export results in cozy-light stopping

### ISSUE THREAD

**Issue by marthjod** [cozy-labs/cozy-light#62]
Reproduce: On, e.g., http://localhost:19104/apps/cozy-contacts/#help, choose "Click here to export all your contacts as a vCard file: Export vCard file". 
Results in uncaught exception and cozy-light stopping:

```
warn - Cozy Light | An exception is uncaught
[ReferenceError: initial is not defined]
ReferenceError: initial is not defined
    at ModelConstructor.Contact.getComputedFN (/home/marcin/.cozy-light/node_modules/cozy-contacts/server/models/contact.js:47:34)
    at ModelConstructor.Contact.toVCF (/home/marcin/.cozy-light/node_modules/cozy-contacts/server/models/contact.js:61:26)
    at /home/marcin/.cozy-light/node_modules/cozy-contacts/server/controllers/contact.js:124:26
    at /home/marcin/.cozy-light/node_modules/cozy-contacts/node_modules/americano-cozy-pouchdb/node_modules/jugglingdb-pouchdb-adapter/lib/pouchdb.js:429:20
    at /usr/lib/node_modules/cozy-light/node_modules/pouchdb/node_modules/pouchdb-mapreduce/utils.js:25:9
    at process._tickCallback (node.js:419:13)
info - Cozy Light | Stopping apps...
info - Cozy Light | 	✓	Contacts
info - Cozy Light | 	✓	Files
info - Cozy Light | Stopping plugins...
info - Cozy Light | 	✓	Simple Dashboard
info - Cozy Light | 	✓	Auth Plugin
info - Cozy Light | Stopping server...
info - Cozy Light | 	✓	main server
info - Cozy Light | Cozy Light was properly terminated.
GET /contacts.vcf - - ms - -
{ [Error: socket hang up] code: 'ECONNRESET' }
```

**Comment by marthjod** [comment]
Sorry, not the right place to open this issue. I'll defer to https://github.com/cozy/cozy-contacts.

**Comment by maboiteaspam** [comment]
hi,

i re open the issue, seems unexpected and not acceptable the whole system shutdown a buggy app.
Instead, we shall mark the application as buggy, or do something more user friendly like post an issue automatically, or give instructions to do so, TBDefined.

thanks for reporting !
