### ISSUE TITLE
Error when trying to install a distro

### ISSUE THREAD

**Issue by nicodel** [cozy-labs/cozy-light#71]
Hi (again),

I have an error while trying to list or install a distro:
```
~ $ cozy-light install-distro

/usr/local/lib/node_modules/cozy-light/lib/cozy-light.js:105
        if (arguments[arg].commands !== undefined) program = arguments[arg];
                          ^
TypeError: Cannot read property 'commands' of undefined
    at Command.prepareAction (/usr/local/lib/node_modules/cozy-light/lib/cozy-light.js:105:27)
    at Command.listener (/usr/local/lib/node_modules/cozy-light/node_modules/commander/index.js:249:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/cozy-light/node_modules/commander/index.js:480:12)
    at Command.parse (/usr/local/lib/node_modules/cozy-light/node_modules/commander/index.js:372:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/cozy-light/bin/cozy-light:95:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by nicodel** [comment]
(and `/` is not full)

**Comment by nicodel** [comment]
I updated cozy-light on my RPI and I was able to install a distro. Case closed :)

**Comment by frankrousseau** [comment]
great!
