### ISSUE TITLE
Fix tests and build checkup

### ISSUE THREAD

**Issue by nicodel** [cozy-labs/cozy-light#79]
Hi,
`npm test` keeps throwing the same errors:
```
  6 passing (18s)
  1 pending
  2 failing

  1) CLI displays content properly:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at Request._callback (/home/nicodel/workspace/cozy/cozy-light/test/cli.js:135:13)
      at self.callback (/home/nicodel/workspace/cozy/cozy-light/node_modules/request/request.js:344:22)
      at Request.emit (events.js:95:17)
      at Request.onRequestError (/home/nicodel/workspace/cozy/cozy-light/node_modules/request/request.js:961:8)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.emit (events.js:95:17)
      at net.js:440:14
      at process._tickCallback (node.js:419:13)

  2) CLI can stop properly:

      Uncaught AssertionError: expected 7 to equal 0
      + expected - actual

      +0
      -7
      
      at Assertion.fail (/home/nicodel/workspace/cozy/cozy-light/node_modules/should/lib/assertion.js:228:17)
      at Assertion.prop.(anonymous function) [as eql] (/home/nicodel/workspace/cozy/cozy-light/node_modules/should/lib/assertion.js:69:14)
      at ChildProcess.<anonymous> (/home/nicodel/workspace/cozy/cozy-light/test/cli.js:152:21)
      at ChildProcess.emit (events.js:98:17)
      at maybeClose (child_process.js:755:16)
      at Process.ChildProcess._handle.onexit (child_process.js:822:5)



npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```
It would be great to, or solve these problems if the fails are true, or fix the test scripts, if the fails are not real ones.

**Comment by nicodel** [comment]
#80 is fixing some errors.
But build for windows machines stil fails.

**Comment by frankrousseau** [comment]
We should add tests for Node 0.12 and io.js too.
