### ISSUE TITLE
[cozy-files] Download folder as zip broken

### ISSUE THREAD

**Issue by hominhquan** [cozy-labs/cozy-light#83]
File downloading has no problem, but when I choose to download a folder (as zip), the openned link is broken. Cozy-light then caught an exception and crash : 

``` python
[33mwarn[39m  - An uncaught exception has been thrown:
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
[34minfo[39m  - Stopping apps...
[33mwarn[39m  - An uncaught exception has been thrown:
{ [Error: socket hang up] code: 'ECONNRESET' }
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:465:12)
```

**Comment by frankrousseau** [comment]
Ok I think the Files version of Cozy Light is old now. We should update it and it will fix that problem.

**Comment by hominhquan** [comment]
Thanks for response. I'm looking forward to a new version soon. :)
